import js from "@eslint/js";
import tsPlugin from "@typescript-eslint/eslint-plugin";
import tsParser from "@typescript-eslint/parser";

export default [
  {
    // `styled-system/` is generated by `panda codegen` and gitignored. Linting
    // it reports errors in code nobody wrote and nobody can fix without editing
    // output that is rebuilt on the next run.
    ignores: [
      "node_modules/**",
      "coverage/**",
      "dist/**",
      "styled-system/**",
      "demo/dist/**",
      "demo/node_modules/**",
    ],
  },
  js.configs.recommended,
  {
    files: ["src/**/*.ts", "src/**/*.tsx"],
    languageOptions: {
      parser: tsParser,
      parserOptions: {
        ecmaVersion: "latest",
        sourceType: "module",
        ecmaFeatures: { jsx: true },
      },
    },
    plugins: { "@typescript-eslint": tsPlugin },
    rules: {
      ...tsPlugin.configs.recommended.rules,
      "@typescript-eslint/no-unused-vars": [
        "error",
        { argsIgnorePattern: "^_", varsIgnorePattern: "^_" },
      ],
      // `--fix` is deliberately not wired into any build script here: a build
      // that rewrites tracked sources hides from review the very errors review
      // exists to catch, and leaves the fix uncommitted so it returns on the
      // next checkout.
    },
  },
  {
    // The demo is linted too. It is not published, but it is the worked example
    // consumers copy from — and a directory excluded from the gate is a
    // directory where the gate's findings do not apply, which nobody remembers
    // when reading it.
    files: ["demo/**/*.{ts,tsx}"],
    languageOptions: {
      parser: tsParser,
      parserOptions: {
        ecmaVersion: "latest",
        sourceType: "module",
        ecmaFeatures: { jsx: true },
      },
      globals: {
        // The browser half. Listed explicitly rather than pulled from `globals`
        // so the demo adds no dependency the package does not already have.
        window: "readonly",
        document: "readonly",
        fetch: "readonly",
        URL: "readonly",
        URLSearchParams: "readonly",
        AbortController: "readonly",
        AbortSignal: "readonly",
        Response: "readonly",
      },
    },
    plugins: { "@typescript-eslint": tsPlugin },
    rules: {
      ...tsPlugin.configs.recommended.rules,
      "@typescript-eslint/no-unused-vars": [
        "error",
        { argsIgnorePattern: "^_", varsIgnorePattern: "^_" },
      ],
      // `no-undef` cannot see TypeScript's own type-only globals and reports
      // false positives on them; `tsc` covers what it would have caught.
      "no-undef": "off",
    },
  },
  {
    files: ["src/**/__tests__/**/*.{ts,tsx}"],
    languageOptions: {
      globals: {
        describe: "readonly",
        it: "readonly",
        expect: "readonly",
        // The integration tier resolves its fixture directory from the working
        // directory, which the unit tiers never need.
        process: "readonly",
      },
    },
  },
];
