/** @type {import('jest').Config} */
module.exports = {
  // ESM, not the default CJS transform. Every markdown dependency in this
  // package's tree — unified, remark-*, mdast-*, unist-*, github-slugger — is
  // ESM-only, and the CJS path can only load them by adding each one (and each
  // of their transitive micromark/vfile helpers) to a transformIgnorePatterns
  // allowlist that silently rots as the tree changes. Running Jest as ESM lets
  // Node resolve them the way the published package will.
  //
  // Requires NODE_OPTIONS=--experimental-vm-modules, set in the `test` script.
  preset: "ts-jest/presets/default-esm",
  // `.tsx` as well as `.ts`. Omitting it loads the component modules as
  // CommonJS, where the first ESM-only import fails with "Must use import to
  // load ES Module" — pointing at the dependency rather than at this list.
  extensionsToTreatAsEsm: [".ts", ".tsx"],
  testEnvironment: "node",
  moduleNameMapper: {
    // Source imports carry `.js` specifiers because that is what real ESM
    // requires of the published package. TypeScript resolves them back to `.ts`
    // itself; Jest does not, so the extension is stripped here.
    "^(\\.{1,2}/.*)\\.js$": "$1",
    // `styled-system` is generated by `panda codegen` into the repo root and
    // resolved via tsconfig baseUrl at typecheck time. Jest does not read
    // baseUrl, so it needs the mapping spelled out or every styled import dies
    // with "Cannot find module 'styled-system/css'".
    "^styled-system/(.*)$": "<rootDir>/styled-system/$1",
    // The demo imports the package by its public specifier, as a consumer does.
    // Anchored with `$` so the bare entry point cannot swallow the subpaths.
    //
    // This is the THIRD place these three aliases are written — `resolve.alias`
    // in demo/vite.config.ts and `paths` in demo/tsconfig.json are the others.
    // They must agree, and each exists because the tool reading it knows
    // nothing of the other two. All three point at `src/`, which is what stops
    // the demo silently exercising the published 0.1.1 instead of this branch.
    "^@stonedogcode/howto$": "<rootDir>/src/index.ts",
    "^@stonedogcode/howto/node$": "<rootDir>/src/node/index.ts",
    "^@stonedogcode/howto/styled$": "<rootDir>/src/styled/index.ts",
  },
  transform: {
    "^.+\\.tsx?$": ["ts-jest", { useESM: true }],
  },
  // `@stonedogcode/style` ships TypeScript SOURCE rather than a bundle (Panda has to
  // statically parse it at the consumer's build). Jest does not transform
  // node_modules by default, so its `.ts` files reach Node's ESM loader raw and
  // fail on the first `export type`. It is named explicitly rather than opening
  // node_modules wholesale: everything else in this tree is already ESM and
  // needs no transform, and transforming all of it would be slow for nothing.
  transformIgnorePatterns: ["/node_modules/(?!@stonedogcode/style/)", "\\.pnp\\.[^\\\\]+$"],
  testMatch: ["<rootDir>/src/**/__tests__/**/*.test.{ts,tsx}"],
  collectCoverageFrom: [
    "src/**/*.{ts,tsx}",
    "!src/**/__tests__/**",
    "!src/index.ts",
  ],
};
